import { useState, useEffect } from 'react';
import { useSearchParams } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { FileText, Send, AlertCircle, Copy, CheckCircle2, Download, Share2 } from 'lucide-react';
import api from '../services/api';
import LoadingSpinner from '../components/common/LoadingSpinner';

const ReportPage = () => {
  const [searchParams] = useSearchParams();
  const [isGenerating, setIsGenerating] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState('');
  const [activeTab, setActiveTab] = useState('objections');
  const [copied, setCopied] = useState(false);
  const [shareMessage, setShareMessage] = useState('');

  const [formData, setFormData] = useState({
    product: '',
    industry: '',
    businessModel: '',
    dealSize: '',
    buyerProfile: '',
    additionalContext: ''
  });

  useEffect(() => {
    const reportId = searchParams.get('id');
    if (reportId) {
      const loadReport = async () => {
        try {
          setIsGenerating(true);
          const res = await api.get(`/reports/${reportId}`);
          if (res.data) {
            setResult(res.data.report_data || res.data);
            setFormData(prev => ({
              ...prev,
              product: res.data.product || prev.product,
              industry: res.data.industry || prev.industry
            }));
          }
        } catch (e) {
          console.warn('Could not load report by id:', e);
          setError('Could not retrieve saved report.');
        } finally {
          setIsGenerating(false);
        }
      };
      loadReport();
    }
  }, [searchParams]);

  const businessModels = ['B2B', 'B2C', 'D2C', 'SaaS', 'Franchise', 'Agency', 'Consulting'];
  const dealSizes = ['<1L', '1-5L', '5-25L', '25L-1Cr', '1Cr+'];
  const buyerProfiles = ['Business Owner', 'CXO', 'Purchase Manager', 'Startup Founder', 'Solopreneur'];

  const handleSelect = (field, value) => {
    setFormData(prev => ({ ...prev, [field]: value }));
  };

  const handleGenerate = async (e) => {
    e.preventDefault();
    if (!formData.product || !formData.industry) {
      setError('Product and Industry are required.');
      return;
    }
    
    setIsGenerating(true);
    setError('');
    
    try {
      const res = await api.post('/reports/generate', {
        product: formData.product,
        industry: formData.industry,
        businessModels: formData.businessModel ? [formData.businessModel] : [],
        dealSize: formData.dealSize || '',
        buyerProfiles: formData.buyerProfile ? [formData.buyerProfile] : [],
        additionalContext: formData.additionalContext || ''
      });
      setResult(res.data.report?.report_data || res.data.report);
      setIsGenerating(false);
    } catch (err) {
      const msg = err.response?.data?.error || 'Failed to generate report. Please try again.';
      setError(msg);
      setIsGenerating(false);
    }
  };

  const copyToClipboard = () => {
    if (result) {
      navigator.clipboard.writeText(JSON.stringify(result, null, 2));
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const downloadReport = () => {
    if (!result) return;
    const reportText = `SALES INTELLIGENCE PLAYBOOK
Product: ${formData.product || 'Solution'}
Industry: ${formData.industry || 'General'}
Generated by SalesIQ (Manuj Bajaj 6KLH Framework)
==================================================

SUMMARY:
${result.summary || 'Strategic objection handling playbook.'}

--------------------------------------------------
OBJECTIONS & 6KLH DEFENSE:
${(result.objections || []).map((cat, idx) => {
  if (cat.items) {
    return `\n[${cat.category || 'Category ' + (idx + 1)}]\n` + cat.items.map(item => 
      `Objection: "${item.objection || item.text}"\n` +
      `The Stab: ${item.stab}\n` +
      `The Twist: ${item.twist}\n` +
      `6KLH Breakdown: ${item.six_klh_breakdown || item.sixKLH}\n` +
      `Closing Pitch: ${item.closing_offer_pitch || item.pitch}\n`
    ).join('\n');
  }
  return `Objection: "${cat.text || cat.objection}"\nStab: ${cat.stab}\nTwist: ${cat.twist}\nPitch: ${cat.pitch}\n`;
}).join('\n')}

--------------------------------------------------
DISCOVERY QUESTIONS:
${(result.client_questions || []).map(cat => {
  if (cat.items) {
    return cat.items.map(q => `Q: "${q.question}"\nWhy they ask: ${q.why_they_ask}\nPower Answer: ${q.power_answer_hint}\n`).join('\n');
  }
  return '';
}).join('\n')}
`;

    const blob = new Blob([reportText], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `SalesIQ-Playbook-${(formData.product || 'Report').replace(/\s+/g, '_')}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    setShareMessage('Report downloaded successfully!');
    setTimeout(() => setShareMessage(''), 3000);
  };

  const shareReport = async () => {
    if (!result) return;
    const shareUrl = window.location.href;
    if (navigator.share) {
      try {
        await navigator.share({
          title: `SalesIQ Playbook: ${formData.product || 'Objection Handling'}`,
          text: `Check out this 6KLH objection playbook for ${formData.product || 'sales deals'}:`,
          url: shareUrl,
        });
        setShareMessage('Shared successfully!');
      } catch (err) {
        if (err.name !== 'AbortError') {
          await navigator.clipboard.writeText(shareUrl);
          setShareMessage('Report link copied to clipboard!');
        }
      }
    } else {
      await navigator.clipboard.writeText(shareUrl);
      setShareMessage('Report link copied to clipboard!');
    }
    setTimeout(() => setShareMessage(''), 3000);
  };

  // Helper renderer for objections
  const renderObjections = () => {
    if (!result?.objections || result.objections.length === 0) {
      return (
        <div className="text-center py-10 text-slate-400">
          <p>No objections returned for this query.</p>
        </div>
      );
    }

    return result.objections.map((group, groupIdx) => {
      if (group.items && Array.isArray(group.items)) {
        return (
          <div key={groupIdx} className="space-y-4">
            <h3 className="text-xs font-bold uppercase tracking-wider text-brand-700 bg-brand-50/80 px-3 py-1.5 rounded-md border border-brand-100 flex items-center gap-2">
              <span className="w-2 h-2 rounded-full bg-brand-500"></span>
              {group.category}
            </h3>
            {group.items.map((obj, i) => (
              <div key={i} className="border border-slate-200 rounded-xl overflow-hidden shadow-xs bg-white">
                <div className="p-5">
                  <h4 className="text-base font-bold text-slate-900 mb-3 flex items-start gap-2">
                    <span className="text-brand-500 font-extrabold text-lg leading-none">“</span>
                    <span>{obj.objection || obj.text}</span>
                  </h4>
                  
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-3.5 mb-3.5">
                    <div className="bg-red-50/70 border border-red-100 rounded-xl p-3.5">
                      <span className="text-[11px] font-bold text-red-700 uppercase tracking-wider mb-1 block">
                        ⚔️ The Stab (Validate & Agree)
                      </span>
                      <p className="text-slate-800 text-xs leading-relaxed">{obj.stab}</p>
                    </div>
                    <div className="bg-emerald-50/70 border border-emerald-100 rounded-xl p-3.5">
                      <span className="text-[11px] font-bold text-emerald-700 uppercase tracking-wider mb-1 block">
                        🎯 The Twist (Cost of Inaction)
                      </span>
                      <p className="text-slate-800 text-xs leading-relaxed">{obj.twist}</p>
                    </div>
                  </div>
                  
                  {(obj.six_klh_breakdown || obj.sixKLH) && (
                    <div className="bg-amber-50/70 border border-amber-100 rounded-xl p-3.5 mb-3.5">
                      <span className="text-[11px] font-bold text-amber-800 uppercase tracking-wider mb-1 block">
                        🧠 6KLH Framework Deconstruction
                      </span>
                      <p className="text-slate-800 text-xs leading-relaxed">{obj.six_klh_breakdown || obj.sixKLH}</p>
                    </div>
                  )}
                  
                  {(obj.closing_offer_pitch || obj.pitch) && (
                    <div className="bg-blue-50/70 border border-blue-100 rounded-xl p-3.5">
                      <span className="text-[11px] font-bold text-blue-800 uppercase tracking-wider mb-1 block">
                        🚀 High-Converting Closing Pitch
                      </span>
                      <p className="text-slate-800 text-xs font-medium leading-relaxed">{obj.closing_offer_pitch || obj.pitch}</p>
                    </div>
                  )}
                </div>
              </div>
            ))}
          </div>
        );
      }

      return (
        <div key={groupIdx} className="border border-slate-200 rounded-xl overflow-hidden shadow-xs">
          <div className="bg-slate-50 px-4 py-2.5 border-b border-slate-200 flex justify-between items-center">
            <span className="text-xs font-bold uppercase tracking-wider text-slate-500">{group.category || 'Objection'}</span>
          </div>
          <div className="p-5">
            <h4 className="text-base font-bold text-slate-900 mb-3">"{group.text || group.objection}"</h4>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3 mb-3">
              <div className="bg-red-50 border border-red-100 rounded-xl p-3">
                <span className="text-xs font-bold text-red-600 uppercase mb-1 block">The Stab</span>
                <p className="text-slate-800 text-xs">{group.stab}</p>
              </div>
              <div className="bg-emerald-50 border border-emerald-100 rounded-xl p-3">
                <span className="text-xs font-bold text-emerald-700 uppercase mb-1 block">The Twist</span>
                <p className="text-slate-800 text-xs">{group.twist}</p>
              </div>
            </div>
            {group.pitch && (
              <div className="bg-blue-50 border border-blue-100 rounded-xl p-3">
                <span className="text-xs font-bold text-blue-700 uppercase mb-1 block">Closing Pitch</span>
                <p className="text-slate-800 text-xs">{group.pitch}</p>
              </div>
            )}
          </div>
        </div>
      );
    });
  };

  // Helper renderer for Discovery Questions
  const renderQuestions = () => {
    const questions = result?.client_questions || [];
    if (questions.length === 0) {
      return (
        <div className="p-6 text-center text-slate-500 bg-slate-50 rounded-xl border border-slate-200">
          <p className="font-semibold text-sm">Key Discovery Questions for {formData.product || 'this solution'}:</p>
          <ul className="text-left text-xs mt-3 space-y-2 max-w-lg mx-auto text-slate-700">
            <li className="p-3 bg-white rounded-lg border border-slate-200">1. "If you don't solve this bottleneck in the next 90 days, what is the conservative financial impact on your team?"</li>
            <li className="p-3 bg-white rounded-lg border border-slate-200">2. "When you evaluated alternatives previously, where did implementation typically stall?"</li>
            <li className="p-3 bg-white rounded-lg border border-slate-200">3. "Who besides yourself will judge whether this initiative is a home run 6 months from now?"</li>
          </ul>
        </div>
      );
    }

    return questions.map((cat, catIdx) => (
      <div key={catIdx} className="space-y-3">
        <h4 className="text-xs font-bold uppercase tracking-wider text-slate-500">{cat.category || 'Strategic Inquiry'}</h4>
        {cat.items?.map((q, i) => (
          <div key={i} className="p-4 rounded-xl border border-slate-200 bg-slate-50/60 hover:bg-white transition-all shadow-2xs">
            <h5 className="font-bold text-slate-900 text-xs mb-1.5 flex items-start gap-2">
              <span className="text-brand-500 font-extrabold">Q:</span>
              <span>{q.question}</span>
            </h5>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-2.5 mt-2.5 text-[11px]">
              <div className="p-2.5 bg-amber-50/80 rounded-lg border border-amber-200/60">
                <span className="font-bold text-amber-800 block mb-0.5">Hidden Buyer Motivation:</span>
                <span className="text-slate-700">{q.why_they_ask}</span>
              </div>
              <div className="p-2.5 bg-brand-50/80 rounded-lg border border-brand-200/60">
                <span className="font-bold text-brand-800 block mb-0.5">Power Rep Rebuttal:</span>
                <span className="text-slate-700">{q.power_answer_hint}</span>
              </div>
            </div>
          </div>
        ))}
      </div>
    ));
  };

  // Helper renderer for Cost of Inaction
  const renderCostOfInaction = () => {
    return (
      <div className="space-y-4">
        <div className="p-4 rounded-xl bg-gradient-to-r from-red-50 to-orange-50 border border-red-200">
          <h4 className="font-bold text-red-900 text-xs mb-1.5 flex items-center gap-2">
            <span>⚠️</span> The "Twist" Mathematical Multiplier
          </h4>
          <p className="text-xs text-red-800 leading-relaxed">
            Prospects who delay decisions by 3 months lose an average of 4.5x the cost of the software license in missed conversions and rep inefficiency. Use these concrete talking points during the Twist phase:
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
          <div className="p-3.5 rounded-xl bg-white border border-slate-200 shadow-2xs">
            <span className="text-xl font-black text-red-600 block mb-0.5">3.8x</span>
            <h5 className="font-bold text-xs text-slate-900 mb-0.5">Delayed Pipeline Slip</h5>
            <p className="text-[11px] text-slate-500 leading-relaxed">
              Every month of delay extends the sales cycle by 14 days and decreases ultimate win rates by 22%.
            </p>
          </div>

          <div className="p-3.5 rounded-xl bg-white border border-slate-200 shadow-2xs">
            <span className="text-xl font-black text-amber-600 block mb-0.5">₹45,000+</span>
            <h5 className="font-bold text-xs text-slate-900 mb-0.5">Monthly Opportunity Cost</h5>
            <p className="text-[11px] text-slate-500 leading-relaxed">
              Unanswered objections cause rep hesitation, leading to discounted deal sizes and lost margin.
            </p>
          </div>

          <div className="p-3.5 rounded-xl bg-white border border-slate-200 shadow-2xs">
            <span className="text-xl font-black text-emerald-600 block mb-0.5">100%</span>
            <h5 className="font-bold text-xs text-slate-900 mb-0.5">Pilot Risk Reversal</h5>
            <p className="text-[11px] text-slate-500 leading-relaxed">
              Position the phased rollout so the prospect experiences positive ROI before final sign-off.
            </p>
          </div>
        </div>

        <div className="p-4 rounded-xl bg-slate-900 text-white">
          <h5 className="text-xs font-bold text-brand-400 uppercase tracking-wider mb-1.5">
            Manuj Bajaj Closing Script:
          </h5>
          <p className="text-xs text-slate-200 italic leading-relaxed">
            "John, if you decide not to proceed today, you save ₹{formData.dealSize || '50,000'} right now. But three months from now, when the same objections keep blocking your reps from hitting their quota, how much revenue did waiting actually cost you? Let's take the first step together today."
          </p>
        </div>
      </div>
    );
  };

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10">
      <div className="mb-8">
        <h1 className="text-3xl font-display font-bold text-slate-900">Generate Intelligence Report</h1>
        <p className="text-slate-500 mt-1">Fill in the details to get a customized 6KLH sales playbook.</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Form Section */}
        <div className="lg:col-span-1">
          <form onSubmit={handleGenerate} className="card p-6 space-y-5 sticky top-24">
            {error && (
              <div className="p-3 rounded-md bg-red-50 border border-red-200 flex items-start text-red-700 text-sm">
                <AlertCircle className="w-4 h-4 mr-2 mt-0.5" />
                {error}
              </div>
            )}

            <div>
              <div className="flex items-center justify-between mb-2">
                <span className="text-xs font-bold text-slate-500 uppercase tracking-wider">⚡ 1-Click Examples:</span>
              </div>
              <div className="flex flex-wrap gap-1.5">
                {[
                  { name: 'Enterprise CRM', ind: 'SaaS / B2B', model: 'B2B', deal: '5-25L', buyer: 'CXO' },
                  { name: 'High-Ticket Coaching', ind: 'Professional Services', model: 'Consulting', deal: '1-5L', buyer: 'Business Owner' },
                  { name: 'AI Marketing Agency', ind: 'Digital Marketing', model: 'Agency', deal: '25L-1Cr', buyer: 'Startup Founder' }
                ].map((sample, idx) => (
                  <button
                    key={idx}
                    type="button"
                    onClick={() => {
                      setFormData(prev => ({
                        ...prev,
                        product: sample.name,
                        industry: sample.ind,
                        businessModel: sample.model,
                        dealSize: sample.deal,
                        buyerProfile: sample.buyer
                      }));
                    }}
                    className="text-[11px] px-2.5 py-1 rounded-md bg-slate-100 hover:bg-brand-50 hover:text-brand-700 hover:border-brand-200 border border-slate-200 text-slate-700 transition-all font-medium"
                  >
                    + {sample.name}
                  </button>
                ))}
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium text-slate-700 mb-1">Product/Service Name *</label>
              <input type="text" className="input-field" value={formData.product} onChange={e => handleSelect('product', e.target.value)} placeholder="e.g. Sales Coaching Program" required />
            </div>

            <div>
              <label className="block text-sm font-medium text-slate-700 mb-1">Industry *</label>
              <input type="text" className="input-field" value={formData.industry} onChange={e => handleSelect('industry', e.target.value)} placeholder="e.g. B2B Services" required />
            </div>

            <div>
              <label className="block text-sm font-medium text-slate-700 mb-2">Business Model</label>
              <div className="flex flex-wrap gap-2">
                {businessModels.map(model => (
                  <button key={model} type="button" onClick={() => handleSelect('businessModel', model)} className={`px-3 py-1.5 rounded-full text-xs font-medium transition-colors ${formData.businessModel === model ? 'bg-brand-500 text-white shadow-sm' : 'bg-slate-100 text-slate-600 hover:bg-slate-200'}`}>
                    {model}
                  </button>
                ))}
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium text-slate-700 mb-2">Deal Size (INR)</label>
              <div className="flex flex-wrap gap-2">
                {dealSizes.map(size => (
                  <button key={size} type="button" onClick={() => handleSelect('dealSize', size)} className={`px-3 py-1.5 rounded-full text-xs font-medium transition-colors ${formData.dealSize === size ? 'bg-brand-500 text-white shadow-sm' : 'bg-slate-100 text-slate-600 hover:bg-slate-200'}`}>
                    {size}
                  </button>
                ))}
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium text-slate-700 mb-2">Buyer Profile</label>
              <div className="flex flex-wrap gap-2">
                {buyerProfiles.map(profile => (
                  <button key={profile} type="button" onClick={() => handleSelect('buyerProfile', profile)} className={`px-3 py-1.5 rounded-full text-xs font-medium transition-colors ${formData.buyerProfile === profile ? 'bg-brand-500 text-white shadow-sm' : 'bg-slate-100 text-slate-600 hover:bg-slate-200'}`}>
                    {profile}
                  </button>
                ))}
              </div>
            </div>

            <div>
              <label className="block text-sm font-medium text-slate-700 mb-1">Additional Context (Optional)</label>
              <textarea className="input-field h-24 resize-none" value={formData.additionalContext} onChange={e => handleSelect('additionalContext', e.target.value)} placeholder="Any specific objections you keep facing?"></textarea>
            </div>

            <button type="submit" disabled={isGenerating} className="w-full btn-primary py-4 text-lg font-bold shadow-brand-500/30">
              {isGenerating ? 'Analyzing...' : (
                <>Generate Playbook <Send className="w-5 h-5 ml-2" /></>
              )}
            </button>
          </form>
        </div>

        {/* Results Section */}
        <div className="lg:col-span-2">
          {isGenerating ? (
            <div className="card h-full min-h-[600px] flex flex-col items-center justify-center p-10 bg-slate-50">
              <LoadingSpinner size="lg" label="" />
              <h3 className="mt-6 text-xl font-display font-bold text-slate-900 animate-pulse">Running 6KLH Algorithm</h3>
              <p className="mt-2 text-slate-500 text-center max-w-sm">
                "An objection is just a request for more information masked as a rejection." - Manuj Bajaj
              </p>
            </div>
          ) : result ? (
            <div className="card h-full border-brand-200 shadow-md">
              <div className="border-b border-slate-200 px-6 py-4 flex flex-col sm:flex-row justify-between items-center bg-slate-50 gap-3">
                <div className="flex space-x-1 w-full sm:w-auto overflow-x-auto pb-2 sm:pb-0">
                  <button onClick={() => setActiveTab('objections')} className={`px-4 py-2 text-xs font-bold rounded-lg whitespace-nowrap transition-all ${activeTab === 'objections' ? 'bg-white text-brand-600 shadow-sm border border-slate-200' : 'text-slate-600 hover:bg-slate-200'}`}>Objections & 6KLH</button>
                  <button onClick={() => setActiveTab('questions')} className={`px-4 py-2 text-xs font-bold rounded-lg whitespace-nowrap transition-all ${activeTab === 'questions' ? 'bg-white text-brand-600 shadow-sm border border-slate-200' : 'text-slate-600 hover:bg-slate-200'}`}>Discovery Questions</button>
                  <button onClick={() => setActiveTab('inaction')} className={`px-4 py-2 text-xs font-bold rounded-lg whitespace-nowrap transition-all ${activeTab === 'inaction' ? 'bg-white text-brand-600 shadow-sm border border-slate-200' : 'text-slate-600 hover:bg-slate-200'}`}>Cost of Inaction</button>
                </div>
                <div className="flex space-x-2 w-full sm:w-auto justify-end">
                  <button onClick={copyToClipboard} className="p-2 text-slate-600 hover:text-brand-600 bg-white border border-slate-200 rounded-lg shadow-sm hover:bg-slate-50 transition-colors" title="Copy to clipboard">
                    {copied ? <CheckCircle2 className="w-4 h-4 text-green-600" /> : <Copy className="w-4 h-4" />}
                  </button>
                  <button onClick={downloadReport} className="p-2 text-slate-600 hover:text-brand-600 bg-white border border-slate-200 rounded-lg shadow-sm hover:bg-slate-50 transition-colors" title="Download report">
                    <Download className="w-4 h-4" />
                  </button>
                  <button onClick={shareReport} className="p-2 text-slate-600 hover:text-brand-600 bg-white border border-slate-200 rounded-lg shadow-sm hover:bg-slate-50 transition-colors" title="Share report">
                    {shareMessage ? <CheckCircle2 className="w-4 h-4 text-green-600" /> : <Share2 className="w-4 h-4" />}
                  </button>
                </div>
              </div>

              {shareMessage && (
                <div className="bg-emerald-50 px-6 py-2 border-b border-emerald-100 text-xs font-semibold text-emerald-700 flex items-center justify-between">
                  <span>{shareMessage}</span>
                  <button onClick={() => setShareMessage('')} className="text-emerald-500 hover:text-emerald-800">×</button>
                </div>
              )}
              
              <div className="p-6 bg-white min-h-[500px]">
                <AnimatePresence mode="wait">
                  <motion.div
                    key={activeTab}
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: -10 }}
                    transition={{ duration: 0.2 }}
                  >
                    {activeTab === 'objections' && (
                      <div className="space-y-6">
                        {renderObjections()}
                      </div>
                    )}

                    {activeTab === 'questions' && (
                      <div className="space-y-4">
                        {renderQuestions()}
                      </div>
                    )}

                    {activeTab === 'inaction' && (
                      <div className="space-y-4">
                        {renderCostOfInaction()}
                      </div>
                    )}
                  </motion.div>
                </AnimatePresence>
              </div>
            </div>
          ) : (
            <div className="card h-full min-h-[600px] flex flex-col items-center justify-center p-10 bg-slate-50 border-dashed border-2 border-slate-200">
              <FileText className="w-16 h-16 text-slate-300 mb-4" />
              <h3 className="text-xl font-display font-bold text-slate-700">Ready to Generate</h3>
              <p className="text-slate-500 text-center max-w-sm mt-2">
                Fill out the form on the left to generate your personalized sales intelligence playbook.
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default ReportPage;
